# Generated by Django 2.2.5 on 2019-11-04 05:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialisation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'specialisation',
                'verbose_name_plural': 'specialisations',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('address', models.TextField(blank=True, max_length=5000, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('rating', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('email', models.EmailField(blank=True, help_text='Please enter valid email address, it will be used for verification.', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Please enter valid phone number.', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919999999999'.", regex='^\\+?1?\\d{9,15}$')])),
                ('verified', models.BooleanField(default=False)),
                ('specialisation', models.ManyToManyField(related_name='speciality_of_hospital', to='hospital.Specialisation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'ordering': ('-rating',),
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('address', models.TextField(blank=True, max_length=5000, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('rating', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='hospital.Hospital')),
                ('specialisation', models.ManyToManyField(related_name='speciality', to='hospital.Specialisation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateTimeField(blank=True, help_text='You can choose dates from now', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='You can choose appointment duration as maximum of 7 days', null=True)),
                ('patients_remarks', models.TextField(blank=True, null=True)),
                ('doctors_remarks', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('rejection_cause', models.TextField(blank=True, max_length=20000, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.Doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.Profile')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ('-start_date',),
            },
        ),
    ]
